#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}}
REPO=${REPO:-rancher}

cp ../bin/cniglue .
docker build -t ${REPO}/cniglue:${TAG} .

echo Built ${REPO}/cniglue:${TAG}
